version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Node/npm packages (optional, if you have a package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
