name: BuildandPublishDocker
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'Dockerfile-alpine'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'Dockerfile-alpine'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    # Run this job only if 'Dockerfile' is modified
    if: contains(github.event.head_commit.message, 'Dockerfile') || github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'Dockerfile')
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Build the Ubuntu-based Docker image
      - name: Build Ubuntu Docker image
        run: docker build -f Dockerfile -t brucewillke/docker-fast-cli:ubuntu-latest .

      # Test the Ubuntu-based Docker image
      - name: Test Ubuntu Docker image
        run: |
          docker run --name test-ubuntu -d brucewillke/docker-fast-cli:ubuntu-latest
          docker exec test-ubuntu fast --version
          docker rm -f test-ubuntu

      # Publish the Ubuntu-based Docker image
      - name: Publish Ubuntu Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: brucewillke/docker-fast-cli
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ubuntu-latest

  build-alpine:
    runs-on: ubuntu-latest
    # Run this job only if 'Dockerfile-alpine' is modified
    if: contains(github.event.head_commit.message, 'Dockerfile-alpine') || github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'Dockerfile-alpine')
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Build the Alpine-based Docker image
      - name: Build Alpine Docker image
        run: docker build -f Dockerfile-alpine -t brucewillke/docker-fast-cli:alpine-latest .

      # Test the Alpine-based Docker image
      - name: Test Alpine Docker image
        run: |
          docker run --name test-alpine -d brucewillke/docker-fast-cli:alpine-latest
          docker exec test-alpine fast --version
          docker rm -f test-alpine

      # Publish the Alpine-based Docker image
      - name: Publish Alpine Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: brucewillke/docker-fast-cli
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: alpine-latest
